### ISSUE TITLE
og:image not linked to media

### ISSUE THREAD

**Issue by meinmotion** [mplodowski/seomanager-plugin-public#26]
It looks like the og:image field is now set as a **media finder** field. This is causing two issues:

- og:image should be &lt;meta property="og:image" content="{{ seoTag.og_image **| media** }}"&gt; | media is missing in the seotags/default.htm
- The width and height are empty and not calculated.

**Comment by mplodowski** [comment]
Fixed in version 4.0.0

**Comment by vshepel** [comment]
> Fixed in version 4.0.0

twitter:image missed

**Comment by mplodowski** [comment]
Fixed in version 4.02.

**Comment by thedoofus** [comment]
Will the fix be getting applied to version 3?

**Comment by thedoofus** [comment]
Can I suggest resolving the og_image path in the component rather than using the twig media function?

This is because if you overwrite the og_image in the `seo.beforeComponentRender` event, and set it to a path for an image that's not in the media library, such as an image uploaded with the fileupload form field. Then the twig media function isn't going to resolve the correct path.
