### ISSUE TITLE
Translate SEO

### ISSUE THREAD

**Issue by gogs85** [mplodowski/seomanager-plugin-public#4]
Hi,
I have problem to get translated Seo tags.
How to fix this problem?

**Comment by mplodowski** [comment]
Currently RainLab.Translate plugin does not allow to translate relations and CMS pages. I think soon this will be resolved.

Right now there is a workaround:

https://github.com/mplodowski/seomanager-plugin-public#multilingual-support-solution

**Comment by charles-tainui** [comment]
hello,

@mplodowski : do you plan any update in order to support CMS page fields translations ?
Moreover i'm wondering why, on CMS page, meta keywords is NOT translatable wereas meta description is ?

<img width="717" alt="Capture d’écran 2019-10-06 à 17 18 42" src="https://user-images.githubusercontent.com/14839037/66271379-8acffd80-e85d-11e9-9f9d-d2a96f1123a9.png">

thanks by advance

**Comment by mplodowski** [comment]
Hi,

I managed to fix this issue. It will be available in next build I am working on.
